feat: Resolve environment variables using Ref and --parameters
duartemendes/aws-sam-api-proxy pull request #9
Opened 2020-08-20 11:20 UTC by cjol

This PR introduces a `--parameters` parameter which is used to resolve `!Ref` intrinsic functions within the template. Currently this is only used to resolve `!Ref`s inside a `Environment.Variables` section.

Possible breaking changes:
 - `!Ref MyVar` is no longer transformed to `"Ref MyVar" but instead to `{Ref: "MyVar"}`. I don't know if any other parts of the code rely on this value being a string.
 - Environment variables which are defined as static strings in the template are now passed to functions (I would consider this a bugfix rather than a breaking change!)

Closes #8

2020-08-21 21:30 UTC, duartemendes requested changes
Code looks super neat, tests are also great, thank you!

One change that I want to propose is to change the name and format of the new cli parameter.

I do like the way you did it but the goal here is to keep consistency with `sam` cli, maintaing compatibilitiy and thus allowing users to switch between our proxy and sam cli easier.

`--parameters key1=value1,key2=value2` would become `--parameter-overrides ParameterKey=key1,ParameterValue=value1 ParameterKey=key2,ParameterValue=value2`.

I do think `sam` way is uglier and slightly more complicated but I also think keeping consistency is really important here.

Let me know what you think please.

2020-08-21 21:30 UTC, duartemendes commented on src/parseSAMTemplate/index.js
> +import { yamlParse } from 'yaml-cfn';
Nice one, don't know how I didn't found this package earlier 👌

2020-08-22 06:28 UTC, cjol commented on src/parseSAMTemplate/index.js
> +import { yamlParse } from 'yaml-cfn';
Yeah it's handy! Arguably we don't need parseSamTemplate anymore. I don't know how you feel about just removing it?

2020-08-22 06:30 UTC, cjol commented
I think changing to --parameter-overrides in the format you suggested makes sense. I thought about doing it that way first but then I realised SAM is already inconsistent with CloudFormation so either way we're inconsistent with something. But overall I agree we might as well.be consistent with one of them, and SAM is the primary use case here.

I'm not going to be around to make those changes for the next week or so. Feel free to leave the PR open for me to come back to, or take over and make the changes directly.

2020-08-23 08:50 UTC, duartemendes commented
Actually, just now I realised that this feature doesn't reflect what `--parameter-overrides` does. So keeping consistency with the name is pointless. I do see a problem if later we want to tackle sam's `--parameter-overrides` feature, we would have to use another name or do a breaking change. So since this feature is about overriding environment variables, what about renaming it to `--env-vars-overrides`, given that we already use `--env-vars` for the file?

Or maybe something like `--ref-overrides`? I'm happy to make this change, just want an opinion first @cjol :)

Regarding the format, `sam` seems to support both ways `ParameterKey=key,ParameterValue=value` and `key=value`. So I'm happy with keeping as is and we could optional add support for the first option or just do it later when needed/requested.

2020-08-23 08:50 UTC, duartemendes commented on src/parseSAMTemplate/index.js
> +import { yamlParse } from 'yaml-cfn';
Yeah I think it makes sense to just remove it 👌

2020-08-23 09:41 UTC, duartemendes commented on src/parseSAMTemplate/index.js
> +import { yamlParse } from 'yaml-cfn';
done!

2020-08-30 12:57 UTC, cjol commented
I think `--ref-overrides` makes most sense as a suggestion. Customising the environment vars is (potentially) just one application of using !Ref like this, so I don't think `env-vars-*` is so good.

2020-09-01 21:45 UTC, duarte-airsiders commented
Thank you @cjol, I'll try to wrap this up this week.

2020-09-01 21:47 UTC, duartemendes commented
Thank you @cjol, I'll try to wrap this up this week.

2020-09-07 23:03 UTC, duartemendes approved these changes

2020-09-07 23:05 UTC, merged

2020-09-07 23:39 UTC, duartemendes commented
@cjol thank you again for your work and sorry it took me some time to wrap this up. This has now been published as of version 0.0.15.